# Azure build pipelines for Sysinternalsebpf

resources:
  repositories:
  - repository: SysinternalsEBPF
    type: github
    endpoint: sysinternals
    name: EvgenTat/sysinternalsebpf

trigger:
    branches:
      include:
        - release/*
        - main
      exclude:
        - dev/*
        - test/*
  
pr:
- main

stages:
 - stage: "Build"
   jobs: 
    - job: "Build_Sysinternalsebpf_Ubuntu_20_04_Package"
      pool: 
        name: "SMARTSentinel Agent Build Pool"
        demands:
        - SYSINT_TOOL -equals sysmon   
        - SYSINT_DISTRIBUTION -equals ubuntu_20_04
        - SYSINT_ARCHITECTURE -equals x86_64
      steps:
      - checkout: SysinternalsEBPF
        persistCredentials: true

      - template: templates/build.yaml
      displayName: "Build Sysinternalsebpf"
      
      - task: CopyFiles@2
        displayName: 'stage Sysinternalsebpf'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/build'
          Contents: 'libsysinternalsEBPFinstaller'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'