# Azure build pipelines for Sysinternalsebpf

resources:
  repositories:
  - repository: SysinternalsEBPF
    type: github
    endpoint: sysinternals
    name: EvgenTat/sysinternalsebpf

trigger:
    branches:
      include:
        - release/*
        - main
      exclude:
        - dev/*
        - test/*
  
pr:
- main

stages:
 - stage: "Build"
   jobs: 
    - job: "Build_Sysinternalsebpf_Ubuntu_20_04_Package"
      pool: 
        name: "SMARTSentinel Agent Build Pool"
        demands:
        - SYSINT_TOOL -equals sysmon   
        - SYSINT_DISTRIBUTION -equals ubuntu_20_04
        - SYSINT_ARCHITECTURE -equals x86_64

      steps:
      - checkout: SysinternalsEBPF
        persistCredentials: true

      - template: templates/build.yaml
      - task: CopyFiles@2
        displayName: 'copy Sysinternalsebpf'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)/build'
          Contents: 'libsysinternalsEBPFinstaller'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
      - task: UniversalPackages@0
        displayName: Universal Publish
        inputs:
          command: 'publish'
          publishDirectory: '$(Build.ArtifactStagingDirectory)'
          feedsToUsePublish: 'internal'
          vstsFeedPublish: '165da500-5026-4d8b-9511-dd2994c0bcee/546f5562-af2c-4074-a581-9c5a9b901854'
          vstsFeedPackagePublish: 'libsysinternals-ebpf-linux-x86_64'
          versionOption: 'custom'
          versionPublish: '1.0.2'
          packagePublishDescription: 'Sysinternals EBPF for Linux'